# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "kf_compile_tool"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
configparser = "3"
thiserror = "1"
