pub const LINE_SEPARATOR: &str = "\n######################################################\n";

/// KF1 file extensions.
pub const UNREAL_PACKAGES: [&str; 4] = [".u", ".ucl", ".u.uz2", ".int"];
/// Filter for files-directories, so we copy-paste only source files.
pub const IGNORE_LIST: [&str; 4] = [".git", "*.md", "Docs", "LICENSE"];
/// Alternative folder name, instead of `Classes`. Used to organize source files in a better way.
pub const ALT_SOURCE_DIR_NAME: &str = "sources";

/// Included default config file.
pub const STEAM_APPID_TXT: &str = "steam_appid.txt";

pub mod config_files {
    /// Default app config content.
    pub const APP_CONFIG_TEMPLATE: &str = r";= Home repo: https://github.com/InsultingPros/KFCompileTool
[Global]
mutatorName=BitCore
dir_Compile=D:\Games\KF Dedicated Server
dir_Classes=D:\Documents\Killing Floor Archive\03. Projects\Mods
dir_Redirect=D:\Games\KF Dedicated Server\Redirect
dir_MoveTo=D:\Games\SteamLibrary\steamapps\common\KillingFloor
dir_ReleaseOutput=C:\Users\Pepe User\Desktop\Mutators

[BitCore]
EditPackages=BitCore
bICompileOutsideofKF=True
bAltDirectories=False
bMoveFiles=False
bCreateINT=True
bMakeRedirect=True
bMakeRelease=True
";
    /// App config's global section name.
    pub const GLOBAL_SECTION_NAME: &str = "global";
    /// Config name.
    pub const APP_CONFIG_NAME: &str = "kf_compile_tool.ini";

    /// included minimal kf.ini for ucc.exe
    pub const COMPILATION_CONFIG_TEMPLATE: &str = r";= WARNING! This file is generated by kf_compile_tool and and is meant to be one time use.
[Engine.Engine]
EditorEngine=Editor.EditorEngine

[Core.System]
CacheRecordPath=../System/*.ucl
Paths=../System/*.u
Paths=../Maps/*.rom
Paths=../TestMaps/*.rom
Paths=../Textures/*.utx
Paths=../Sounds/*.uax
Paths=../Music/*.umx
Paths=../StaticMeshes/*.usx
Paths=../Animations/*.ukx
Paths=../Saves/*.uvx
Paths=../Textures/Old2k4/*.utx
Paths=../Sounds/Old2k4/*.uax
Paths=../Music/Old2k4/*.umx
Paths=../StaticMeshes/Old2k4/*.usx
Paths=../Animations/Old2k4/*.ukx
Paths=../KarmaData/Old2k4/*.ka
Suppress=DevLoad
Suppress=DevSave

[ROFirstRun]
ROFirstRun=1094

[Editor.EditorEngine]
EditPackages=Core
EditPackages=Engine
EditPackages=Fire
EditPackages=Editor
EditPackages=UnrealEd
EditPackages=IpDrv
EditPackages=UWeb
EditPackages=GamePlay
EditPackages=UnrealGame
EditPackages=XGame
EditPackages=XInterface
EditPackages=XAdmin
EditPackages=XWebAdmin
EditPackages=GUI2K4
EditPackages=xVoting
EditPackages=UTV2004c
EditPackages=UTV2004s
EditPackages=ROEffects
EditPackages=ROEngine
EditPackages=ROInterface
EditPackages=Old2k4
EditPackages=KFMod
EditPackages=KFChar
EditPackages=KFGui
EditPackages=GoodKarma
EditPackages=KFMutators
EditPackages=KFStoryGame
EditPackages=KFStoryUI
EditPackages=SideShowScript
EditPackages=FrightScript
";
    /// config name
    pub const COMPILATION_CONFIG_NAME: &str = "kfcompile.ini";
}
