name: Debug Build

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  start:
    strategy:
      fail-fast: false

    name: Start `cargo build / test` on Windows
    runs-on: windows-11-arm

    env:
      CARGO_INCREMENTAL: 0
      CARGO_PROFILE_TEST_DEBUG: 0
      CARGO_TERM_COLOR: always
      RUST_BACKTRACE: full

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust Toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Set up Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: v0-rust
          shared-key: kf_compile_tool
          cache-targets: true
          cache-all-crates: true
          cache-on-failure: true

      - name: Build Debug
        run: cargo build --locked
