name: Publish

permissions:
  contents: write

on:
  release:
    types: [created]

jobs:
  publish-rust:
    name: Publish for Windows
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust Toolchain
        uses: dtolnay/rust-toolchain@stable

      # can't use caches in tag scope... thanks github!
      - name: Publish CLI Binary
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          locked: true
          # (required) Comma-separated list of binary names (non-extension portion of filename) to build and upload.# Note that glob pattern is not supported yet.
          bin: kf_compile_tool
          # (optional) On which platform to distribute the .tar.gz file.# [default value: unix]# [possible values: all, unix, windows, none]
          zip: windows
          archive: $bin-$tag-$target
          token: ${{ secrets.GITHUB_TOKEN }}
